MODEL:
  META_ARCHITECTURE: "OvrRCNN"
  WEIGHTS: "models/lsm_coco.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 2
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  # Trim the prefix of the checkpoint parameter names so they can be correctly loaded
  BACKBONE_PREFIX: ("backbone.body.",)
  # Whether to load the vl_projection layer from the multimedia self-supervised learning head
  # If true, it loads it from the default mmss head defined by MODEL.MMSS_HEAD.DEFAULT_HEAD
  LOAD_EMB_PRED_FROM_MMSS_HEAD: True
  ROI_HEADS:
    NAME: "EmbeddingRes5ROIHeads"
    # Number of foreground classes
    NUM_CLASSES: 48
    # Target fraction of RoI minibatch that is labeled foreground (i.e. class > 0)
    # At most how much of a batch should be filled with positive boxes. In zero-shot setting
    # having too many background hurts. Note 1.0 doesn't mean there won't be any background.
    # It is unlikely to have 512 positive boxes, and the rest is always filled with background.
    POSITIVE_FRACTION: 1.0
  ROI_BOX_HEAD:
    NAME: "EmbeddingFastRCNNOutputLayers"
    # Whether to use class agnostic for bbox regression
    CLS_AGNOSTIC_BBOX_REG: True
    # Dimension of embeddings that will be loaded (300 for Glove, 768 for Bert)
    EMB_DIM: 768
    # Always true for zero-shot
    EMBEDDING_BASED: True
    # Whether or not to freeze the vl_projection layer. True is better. Only works if
    # MODEL.LOAD_EMB_PRED_FROM_MMSS_HEAD is true
    FREEZE_EMB_PRED: True
DATASETS:
  TRAIN: ("coco_zeroshot_train",)
  TEST: ("coco_generalized_zeroshot_val", "coco_zeroshot_val", "coco_not_zeroshot_val", )
SOLVER:
  IMS_PER_BATCH: 24 #16
  BASE_LR: 0.005
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 1000
  LOG_PERIOD: 100
TEST:
  EVAL_PERIOD: 5000
  DO_EVAL: False
  IMS_PER_BATCH: 1 #8 #16 #24 #64
  EVAL_INIT: True
  SAVE_MODEL_BEST_METRIC: "coco_zeroshot_val/bbox/AP"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
SEED: 1992
OUTPUT_DIR: "/work/dlclarge1/bravoma-wsog/locov/stt"
